version: '3.5'
services:
  dev:
    user: root
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - ./:/usr/src/langchain_ai_skills_framework
    working_dir: /usr/src/langchain_ai_skills_framework
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - SKILLS_DIRECTORY=github://icanbwell/language-model-gateway-configuration/configs/skills?ref=add-skills
